### ISSUE TITLE
제출기한 문의드립니다

### ISSUE THREAD

**Issue by sj0724** [Allra-Fintech/front-end-assignment#1]
오늘 과제전형 메일받게 되었는데, 오늘(11일)부터 수요일(13일)까지 예비군 동원훈련을 받고있습니다. 혹시 과제 제출일 조정이 가능할지 문의드립니다.
@sangmin4208

**Comment by sangmin4208** [comment]
@sj0724 넵 그럼 수요일 시작으로 조정해드리겠습니다 :)

**Comment by sangmin4208** [comment]
@sj0724 이 부분은 메일을 통해서 다시 말씀해주시겠어요?

**Comment by sj0724** [comment]
답변 감사합니다 이슈 닫겠습니다
